# Generated by Django 3.0 on 2020-09-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
